// Generated by gencpp from file mushr_rhc/XYHVPath.msg
// DO NOT EDIT!


#ifndef MUSHR_RHC_MESSAGE_XYHVPATH_H
#define MUSHR_RHC_MESSAGE_XYHVPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mushr_rhc/XYHV.h>

namespace mushr_rhc
{
template <class ContainerAllocator>
struct XYHVPath_
{
  typedef XYHVPath_<ContainerAllocator> Type;

  XYHVPath_()
    : header()
    , waypoints()  {
    }
  XYHVPath_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::mushr_rhc::XYHV_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mushr_rhc::XYHV_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::mushr_rhc::XYHVPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mushr_rhc::XYHVPath_<ContainerAllocator> const> ConstPtr;

}; // struct XYHVPath_

typedef ::mushr_rhc::XYHVPath_<std::allocator<void> > XYHVPath;

typedef boost::shared_ptr< ::mushr_rhc::XYHVPath > XYHVPathPtr;
typedef boost::shared_ptr< ::mushr_rhc::XYHVPath const> XYHVPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mushr_rhc::XYHVPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mushr_rhc::XYHVPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mushr_rhc::XYHVPath_<ContainerAllocator1> & lhs, const ::mushr_rhc::XYHVPath_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mushr_rhc::XYHVPath_<ContainerAllocator1> & lhs, const ::mushr_rhc::XYHVPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mushr_rhc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mushr_rhc::XYHVPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mushr_rhc::XYHVPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mushr_rhc::XYHVPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mushr_rhc::XYHVPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mushr_rhc::XYHVPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mushr_rhc::XYHVPath_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mushr_rhc::XYHVPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "809d76babfb4692a2ac3d65a1d0c301b";
  }

  static const char* value(const ::mushr_rhc::XYHVPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x809d76babfb4692aULL;
  static const uint64_t static_value2 = 0x2ac3d65a1d0c301bULL;
};

template<class ContainerAllocator>
struct DataType< ::mushr_rhc::XYHVPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mushr_rhc/XYHVPath";
  }

  static const char* value(const ::mushr_rhc::XYHVPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mushr_rhc::XYHVPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"mushr_rhc/XYHV[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mushr_rhc/XYHV\n"
"float64 x\n"
"float64 y\n"
"float64 h\n"
"float64 v\n"
;
  }

  static const char* value(const ::mushr_rhc::XYHVPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mushr_rhc::XYHVPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XYHVPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mushr_rhc::XYHVPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mushr_rhc::XYHVPath_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mushr_rhc::XYHV_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUSHR_RHC_MESSAGE_XYHVPATH_H
