version: "3.4"
services:
  mushr_noetic:
    image: mushr/mushr:${MUSHR_OS_TYPE}
    privileged: true
    volumes:
      - ${MUSHR_WS_PATH}/catkin_ws:/root/catkin_ws # Runtime attach
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - MUSHR_REAL_ROBOT=${MUSHR_REAL_ROBOT}
