version: "3.4"
services:
  mushr_noetic:
    image: mushr/mushr:${MUSHR_OS_TYPE}
    network_mode: "host"
    privileged: true
    devices:
      - "/dev:/dev"
      - "/dev/ydlidar:/dev/ydlidar"
      - "/dev/vesc:/dev/vesc"
      - "/dev/input/js0:/dev/input/js0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - /usr/bin/tegrastats:/usr/bin/tegrastats 
      - /etc/udev:/etc/udev
      - /sys/class/gpio:/sys/class/gpio
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /dev/input:/dev/input
      - ${MUSHR_WS_PATH}/catkin_ws:/root/catkin_ws # Runtime attach
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NEVIAID_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - MUSHR_REAL_ROBOT=${MUSHR_REAL_ROBOT}
