// Generated by gencpp from file mushr_sim/CarPoseRequest.msg
// DO NOT EDIT!


#ifndef MUSHR_SIM_MESSAGE_CARPOSEREQUEST_H
#define MUSHR_SIM_MESSAGE_CARPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mushr_sim
{
template <class ContainerAllocator>
struct CarPoseRequest_
{
  typedef CarPoseRequest_<ContainerAllocator> Type;

  CarPoseRequest_()
    : car_name()
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  CarPoseRequest_(const ContainerAllocator& _alloc)
    : car_name(_alloc)
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _car_name_type;
  _car_name_type car_name;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::mushr_sim::CarPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mushr_sim::CarPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CarPoseRequest_

typedef ::mushr_sim::CarPoseRequest_<std::allocator<void> > CarPoseRequest;

typedef boost::shared_ptr< ::mushr_sim::CarPoseRequest > CarPoseRequestPtr;
typedef boost::shared_ptr< ::mushr_sim::CarPoseRequest const> CarPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mushr_sim::CarPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mushr_sim::CarPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mushr_sim::CarPoseRequest_<ContainerAllocator1> & lhs, const ::mushr_sim::CarPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.car_name == rhs.car_name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mushr_sim::CarPoseRequest_<ContainerAllocator1> & lhs, const ::mushr_sim::CarPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mushr_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mushr_sim::CarPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mushr_sim::CarPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mushr_sim::CarPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mushr_sim::CarPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mushr_sim::CarPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mushr_sim::CarPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mushr_sim::CarPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1488aeaf725b30bccdb21f6950177027";
  }

  static const char* value(const ::mushr_sim::CarPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1488aeaf725b30bcULL;
  static const uint64_t static_value2 = 0xcdb21f6950177027ULL;
};

template<class ContainerAllocator>
struct DataType< ::mushr_sim::CarPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mushr_sim/CarPoseRequest";
  }

  static const char* value(const ::mushr_sim::CarPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mushr_sim::CarPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string car_name\n"
"float32 x\n"
"float32 y\n"
"float32 theta\n"
;
  }

  static const char* value(const ::mushr_sim::CarPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mushr_sim::CarPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.car_name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mushr_sim::CarPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mushr_sim::CarPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "car_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.car_name);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUSHR_SIM_MESSAGE_CARPOSEREQUEST_H
