// Generated by gencpp from file mushr_sim/CarPose.msg
// DO NOT EDIT!


#ifndef MUSHR_SIM_MESSAGE_CARPOSE_H
#define MUSHR_SIM_MESSAGE_CARPOSE_H

#include <ros/service_traits.h>


#include <mushr_sim/CarPoseRequest.h>
#include <mushr_sim/CarPoseResponse.h>


namespace mushr_sim
{

struct CarPose
{

typedef CarPoseRequest Request;
typedef CarPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CarPose
} // namespace mushr_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mushr_sim::CarPose > {
  static const char* value()
  {
    return "d3607be278658b1796ac5e670eba6ac0";
  }

  static const char* value(const ::mushr_sim::CarPose&) { return value(); }
};

template<>
struct DataType< ::mushr_sim::CarPose > {
  static const char* value()
  {
    return "mushr_sim/CarPose";
  }

  static const char* value(const ::mushr_sim::CarPose&) { return value(); }
};


// service_traits::MD5Sum< ::mushr_sim::CarPoseRequest> should match
// service_traits::MD5Sum< ::mushr_sim::CarPose >
template<>
struct MD5Sum< ::mushr_sim::CarPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mushr_sim::CarPose >::value();
  }
  static const char* value(const ::mushr_sim::CarPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mushr_sim::CarPoseRequest> should match
// service_traits::DataType< ::mushr_sim::CarPose >
template<>
struct DataType< ::mushr_sim::CarPoseRequest>
{
  static const char* value()
  {
    return DataType< ::mushr_sim::CarPose >::value();
  }
  static const char* value(const ::mushr_sim::CarPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mushr_sim::CarPoseResponse> should match
// service_traits::MD5Sum< ::mushr_sim::CarPose >
template<>
struct MD5Sum< ::mushr_sim::CarPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mushr_sim::CarPose >::value();
  }
  static const char* value(const ::mushr_sim::CarPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mushr_sim::CarPoseResponse> should match
// service_traits::DataType< ::mushr_sim::CarPose >
template<>
struct DataType< ::mushr_sim::CarPoseResponse>
{
  static const char* value()
  {
    return DataType< ::mushr_sim::CarPose >::value();
  }
  static const char* value(const ::mushr_sim::CarPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUSHR_SIM_MESSAGE_CARPOSE_H
