// Generated by gencpp from file mushr_sim/CarPoseResponse.msg
// DO NOT EDIT!


#ifndef MUSHR_SIM_MESSAGE_CARPOSERESPONSE_H
#define MUSHR_SIM_MESSAGE_CARPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mushr_sim
{
template <class ContainerAllocator>
struct CarPoseResponse_
{
  typedef CarPoseResponse_<ContainerAllocator> Type;

  CarPoseResponse_()
    : success(false)  {
    }
  CarPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::mushr_sim::CarPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mushr_sim::CarPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CarPoseResponse_

typedef ::mushr_sim::CarPoseResponse_<std::allocator<void> > CarPoseResponse;

typedef boost::shared_ptr< ::mushr_sim::CarPoseResponse > CarPoseResponsePtr;
typedef boost::shared_ptr< ::mushr_sim::CarPoseResponse const> CarPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mushr_sim::CarPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mushr_sim::CarPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mushr_sim::CarPoseResponse_<ContainerAllocator1> & lhs, const ::mushr_sim::CarPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mushr_sim::CarPoseResponse_<ContainerAllocator1> & lhs, const ::mushr_sim::CarPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mushr_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mushr_sim::CarPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mushr_sim::CarPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mushr_sim::CarPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mushr_sim::CarPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mushr_sim::CarPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mushr_sim::CarPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mushr_sim::CarPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::mushr_sim::CarPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::mushr_sim::CarPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mushr_sim/CarPoseResponse";
  }

  static const char* value(const ::mushr_sim::CarPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mushr_sim::CarPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::mushr_sim::CarPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mushr_sim::CarPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mushr_sim::CarPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mushr_sim::CarPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUSHR_SIM_MESSAGE_CARPOSERESPONSE_H
